import { Preset } from '../types/synth.types'

export const FACTORY_PRESETS: Preset[] = [
  {
    id: 'init',
    name: 'Init',
    category: 'lead',
    params: {
      master: { volume: -12, attack: 0.01, release: 0.3, waveform: 'sawtooth', octave: 3, mono: false },
      effects: {
        lowpass: { frequency: 20000, Q: 1 },
        highpass: { frequency: 20, Q: 1 },
        reverb: { decay: 1.5, wet: 0 },
        delay: { time: 0.25, feedback: 0.3, wet: 0 },
        distortion: { amount: 0, wet: 0.5 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 2, depth: 0, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0, enabled: false },
      ],
      glide: { enabled: false, time: 0.1 },
      filterEnvelope: { attack: 0.01, decay: 0.2, sustain: 0.5, release: 0.3, amount: 0 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 120 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'classic-bass',
    name: 'Classic Bass',
    category: 'bass',
    params: {
      master: { volume: -8, attack: 0.005, release: 0.2, waveform: 'sawtooth', octave: 2, mono: true },
      effects: {
        lowpass: { frequency: 800, Q: 4 },
        highpass: { frequency: 30, Q: 1 },
        reverb: { decay: 0.5, wet: 0.1 },
        delay: { time: 0.25, feedback: 0.1, wet: 0 },
        distortion: { amount: 0.2, wet: 0.8 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0.6,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 0.5, depth: 0.1, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.2, enabled: true },
      ],
      glide: { enabled: true, time: 0.08 },
      filterEnvelope: { attack: 0.01, decay: 0.3, sustain: 0.2, release: 0.2, amount: 0.5 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 120 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'acid-bass',
    name: 'Acid Bass',
    category: 'bass',
    params: {
      master: { volume: -6, attack: 0.001, release: 0.1, waveform: 'sawtooth', octave: 2, mono: true },
      effects: {
        lowpass: { frequency: 400, Q: 12 },
        highpass: { frequency: 40, Q: 1 },
        reverb: { decay: 0.3, wet: 0.05 },
        delay: { time: 0.375, feedback: 0.4, wet: 0.2 },
        distortion: { amount: 0.4, wet: 1 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 4, depth: 0, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0, enabled: false },
      ],
      glide: { enabled: true, time: 0.05 },
      filterEnvelope: { attack: 0.001, decay: 0.15, sustain: 0.1, release: 0.1, amount: 0.8 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/16', octaves: 1 },
      tempo: { bpm: 130 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'screaming-lead',
    name: 'Screaming Lead',
    category: 'lead',
    params: {
      master: { volume: -10, attack: 0.02, release: 0.4, waveform: 'sawtooth', octave: 4, mono: true },
      effects: {
        lowpass: { frequency: 5000, Q: 2 },
        highpass: { frequency: 100, Q: 1 },
        reverb: { decay: 2, wet: 0.3 },
        delay: { time: 0.375, feedback: 0.35, wet: 0.25 },
        distortion: { amount: 0.3, wet: 0.6 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0.2,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 5, depth: 0.15, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.3, enabled: true },
      ],
      glide: { enabled: true, time: 0.15 },
      filterEnvelope: { attack: 0.05, decay: 0.5, sustain: 0.6, release: 0.5, amount: 0.4 },
      chorus: { rate: 2, depth: 0.4, wet: 0.3 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 120 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'soft-pad',
    name: 'Soft Pad',
    category: 'pad',
    params: {
      master: { volume: -14, attack: 0.5, release: 1.5, waveform: 'triangle', octave: 3, mono: false },
      effects: {
        lowpass: { frequency: 3000, Q: 0.5 },
        highpass: { frequency: 80, Q: 1 },
        reverb: { decay: 5, wet: 0.5 },
        delay: { time: 0.5, feedback: 0.3, wet: 0.15 },
        distortion: { amount: 0, wet: 0.5 },
      },
      oscillator: {
        waveform: 'triangle',
        subOscLevel: 0.3,
        subOscOctave: -1,
        noiseLevel: 0.05,
        noiseType: 'pink',
      },
      lfo: { rate: 0.3, depth: 0.2, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.15, enabled: true },
      ],
      glide: { enabled: false, time: 0.1 },
      filterEnvelope: { attack: 0.8, decay: 1, sustain: 0.7, release: 1.5, amount: 0.3 },
      chorus: { rate: 0.8, depth: 0.6, wet: 0.5 },
      phaser: { rate: 0.2, depth: 0.3, wet: 0.2 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 90 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'warm-strings',
    name: 'Warm Strings',
    category: 'pad',
    params: {
      master: { volume: -12, attack: 0.3, release: 1, waveform: 'square', octave: 3, mono: false },
      effects: {
        lowpass: { frequency: 4000, Q: 1 },
        highpass: { frequency: 100, Q: 1 },
        reverb: { decay: 3, wet: 0.4 },
        delay: { time: 0.25, feedback: 0.2, wet: 0.1 },
        distortion: { amount: 0, wet: 0.5 },
      },
      oscillator: {
        waveform: 'square',
        subOscLevel: 0.15,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 0.8, depth: 0.4, waveform: 'triangle' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.2, enabled: true },
      ],
      glide: { enabled: false, time: 0.1 },
      filterEnvelope: { attack: 0.4, decay: 0.5, sustain: 0.8, release: 1, amount: 0.2 },
      chorus: { rate: 1, depth: 0.5, wet: 0.4 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 120 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'pluck-lead',
    name: 'Pluck Lead',
    category: 'lead',
    params: {
      master: { volume: -10, attack: 0.001, release: 0.5, waveform: 'sawtooth', octave: 4, mono: false },
      effects: {
        lowpass: { frequency: 8000, Q: 1 },
        highpass: { frequency: 80, Q: 1 },
        reverb: { decay: 1.5, wet: 0.25 },
        delay: { time: 0.25, feedback: 0.4, wet: 0.3 },
        distortion: { amount: 0.1, wet: 0.5 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0,
        subOscOctave: -1,
        noiseLevel: 0.02,
        noiseType: 'white',
      },
      lfo: { rate: 2, depth: 0, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0, enabled: false },
      ],
      glide: { enabled: false, time: 0.1 },
      filterEnvelope: { attack: 0.001, decay: 0.2, sustain: 0.3, release: 0.4, amount: 0.6 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/16', octaves: 2 },
      tempo: { bpm: 128 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'wobble-bass',
    name: 'Wobble Bass',
    category: 'bass',
    params: {
      master: { volume: -8, attack: 0.01, release: 0.2, waveform: 'sawtooth', octave: 2, mono: true },
      effects: {
        lowpass: { frequency: 600, Q: 8 },
        highpass: { frequency: 30, Q: 1 },
        reverb: { decay: 0.5, wet: 0.1 },
        delay: { time: 0.25, feedback: 0.1, wet: 0 },
        distortion: { amount: 0.5, wet: 1 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0.4,
        subOscOctave: -1,
        noiseLevel: 0,
        noiseType: 'white',
      },
      lfo: { rate: 3, depth: 0.7, waveform: 'sine' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.8, enabled: true },
      ],
      glide: { enabled: true, time: 0.05 },
      filterEnvelope: { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.2, amount: 0.2 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 0.5, depth: 0.5, wet: 0 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 140 },
      pitchBendRange: 2,
    },
  },
  {
    id: 'laser-fx',
    name: 'Laser FX',
    category: 'fx',
    params: {
      master: { volume: -12, attack: 0.001, release: 0.8, waveform: 'sawtooth', octave: 5, mono: true },
      effects: {
        lowpass: { frequency: 15000, Q: 3 },
        highpass: { frequency: 200, Q: 1 },
        reverb: { decay: 3, wet: 0.4 },
        delay: { time: 0.125, feedback: 0.6, wet: 0.4 },
        distortion: { amount: 0.2, wet: 0.5 },
      },
      oscillator: {
        waveform: 'sawtooth',
        subOscLevel: 0,
        subOscOctave: -2,
        noiseLevel: 0.1,
        noiseType: 'white',
      },
      lfo: { rate: 15, depth: 0.5, waveform: 'sawtooth' },
      modRouting: [
        { target: 'filterCutoff', amount: 0, enabled: false },
      ],
      glide: { enabled: true, time: 0.3 },
      filterEnvelope: { attack: 0.001, decay: 0.5, sustain: 0.2, release: 0.8, amount: 0.7 },
      chorus: { rate: 1.5, depth: 0.5, wet: 0 },
      phaser: { rate: 2, depth: 0.8, wet: 0.5 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 120 },
      pitchBendRange: 12,
    },
  },
  {
    id: 'noise-sweep',
    name: 'Noise Sweep',
    category: 'fx',
    params: {
      master: { volume: -14, attack: 0.5, release: 2, waveform: 'sine', octave: 3, mono: false },
      effects: {
        lowpass: { frequency: 2000, Q: 4 },
        highpass: { frequency: 100, Q: 1 },
        reverb: { decay: 4, wet: 0.6 },
        delay: { time: 0.375, feedback: 0.5, wet: 0.3 },
        distortion: { amount: 0, wet: 0.5 },
      },
      oscillator: {
        waveform: 'sine',
        subOscLevel: 0,
        subOscOctave: -1,
        noiseLevel: 0.8,
        noiseType: 'pink',
      },
      lfo: { rate: 0.1, depth: 0.8, waveform: 'triangle' },
      modRouting: [
        { target: 'filterCutoff', amount: 0.9, enabled: true },
      ],
      glide: { enabled: false, time: 0.1 },
      filterEnvelope: { attack: 2, decay: 1, sustain: 0.5, release: 2, amount: 0.5 },
      chorus: { rate: 0.5, depth: 0.3, wet: 0.3 },
      phaser: { rate: 0.3, depth: 0.6, wet: 0.4 },
      arpeggiator: { enabled: false, pattern: 'up', rate: '1/8', octaves: 1 },
      tempo: { bpm: 100 },
      pitchBendRange: 2,
    },
  },
]
